/*
 * This source file was generated by the Gradle 'init' task
 */
package numer0n;

import numer0n.service.impl.GameManagerImpl;

public class App {

    public static void main(String[] args) {
        GameManagerImpl gameManagerImpl=new GameManagerImpl();
        gameManagerImpl.start();
        // ゲームを開始
    }
}
