/*
 * This source file was generated by the Gradle 'init' task
 */
package numer0n;

import numer0n.service.impl.GameManagerImpl;
import numer0n.service.GameManager;

public class App {

    public static void main(String[] args) {
        GameManager gameManager=new GameManagerImpl();
        gameManager.start();
            
        
       
        // ゲームを開始
    }
}
